from enum import Enum


class PermissionsEnum(Enum):
    # File region
    CAN_CREATE_FILE = "CAN_CREATE_FILE"
    CAN_READ_FILE = "CAN_READ_FILE"
    CAN_UPDATE_FILE = "CAN_UPDATE_FILE"
    CAN_DELETE_FILE = "CAN_DELETE_FILE"

    # Users region
    CAN_CREATE_USERS = "CAN_CREATE_USERS"
    CAN_READ_USERS = "CAN_READ_USERS"
    CAN_UPDATE_USERS = "CAN_UPDATE_USERS"
    CAN_DELETE_USERS = "CAN_DELETE_USERS"
    CAN_READ_ALL_USERS = "CAN_READ_ALL_USERS"
