from enum import Enum


class PermissionsEnum(Enum):
    # Users region
    CAN_CREATE_USERS = "CAN_CREATE_USERS"
    CAN_READ_USERS = "CAN_READ_USERS"
    CAN_UPDATE_USERS = "CAN_UPDATE_USERS"
    CAN_DELETE_USERS = "CAN_DELETE_USERS"
    CAN_READ_ALL_USERS = "CAN_READ_ALL_USERS"

    # Post region
    CAN_CREATE_POSTS = "CAN_CREATE_POSTS"
    CAN_READ_POSTS = "CAN_READ_POSTS"
    CAN_UPDATE_POSTS = "CAN_UPDATE_POSTS"
    CAN_DELETE_POSTS = "CAN_DELETE_POSTS"
    CAN_READ_ALL_POSTS = "CAN_READ_ALL_POSTS"

    # categories region
    CAN_CREATE_CATEGORIES = "CAN_CREATE_CATEGORIES"
    CAN_READ_CATEGORIES = "CAN_READ_CATEGORIES"
    CAN_UPDATE_CATEGORIES = "CAN_UPDATE_CATEGORIES"
    CAN_DELETE_CATEGORIES = "CAN_DELETE_CATEGORIES"
    CAN_READ_ALL_CATEGORIES = "CAN_READ_ALL_CATEGORIES"
