"""fix Post and Category models

Revision ID: 589e8c2d1d01
Revises: b3ad00e6492d
Create Date: 2025-09-28 11:41:27.886206

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "589e8c2d1d01"
down_revision: Union[str, None] = "b3ad00e6492d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_categories_description", "categories", type_="unique")
    op.drop_constraint("uq_posts_body", "posts", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_posts_body", "posts", ["body"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        "uq_categories_description",
        "categories",
        ["description"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
